platform :ios, '10.0'

target 'ECSignerForiOS' do
    use_frameworks!

    pod 'Masonry'
    pod 'MJRefresh'
    pod 'AVOSCloud'
    pod 'YYCache'
    pod 'IQKeyboardManager'
    pod 'ASIHTTPRequest'

end

